import { Suspense } from 'react';
import '../styles/main.scss';
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: 'POS System',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Toaster position="top-center" reverseOrder={false} />
        {children}
      </body>
    </html>
  )
}
